export const LOADING_GET_DATA = 'LOADING_GET_DATA';
export const GET_DATA_MOVIES = 'GET_DATA_MOVIES';
export const GET_DATA_SUCCESSFUL = 'GET_DATA_SUCCESSFUL';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';